baseURL = "http://www.jjedrasik.com"
languageCode = "en-us"
title = "Jan Jedrasik"
theme = "ananke"

[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
[[menu.main]]
  name = "Resume"
  identifier = "resume"
  url = "/resume/"


[params]
github = "https://github.com/jjedrasik"
linkedin = "https://www.linkedin.com/in/jan-jedrasik-bb5209174/"
instagram = "https://www.instagram.com/janjedrasik/?hl=en"
