baseURL = "http://www.jjedrasik.com"
languageCode = "en-us"
title = "Jan Jedrasik"
theme = "ananke"
googleAnalytics = "UA-131914950-1"

[[menu.main]]
  name = "Home"
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
[[menu.main]]
  name = "Resume"
  identifier = "resume"
  url = "/resume/"
[[menu.main]]
  name = "Security Tutorials"
  identifier = "security tutorials"
  url = "/securityTutorials/"
[[menu.main]]
  name = "Virtual Reality"
  identifier = "Virtual Reality"
  url = "/virtualReality/"


[params]
github = "https://github.com/jjedrasik"
linkedin = "https://www.linkedin.com/in/jan-jedrasik-bb5209174/"
instagram = "https://www.instagram.com/janjedrasik/?hl=en"
